model:
  name: "Net"

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  optimizer: "Adam"
  criteriong: 'CrossEntropyLoss'

data:
  train_path: "-"
  val_path: "-"



simulation:
  num_clients: 5
  num_rounds: 1

strategy:
  name: FedAvg
  fraction_fit_: 1.0
  fraction_fit: 1.0
  fraction_evaluate: 0.5
  min_fit_clients: 5
  min_evaluate_clients: 5
  min_available_clients: 5

backend:
  num_cpus: 1
  num_gpus: 1.0
  device: "cuda"


